
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fahim
 */
public class Length extends javax.swing.JFrame {

    /**
     * Creates new form Length
     */
    public Length() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        a = new javax.swing.JComboBox();
        b = new javax.swing.JComboBox();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Length", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Broadway", 1, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        a.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        a.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meter", "Kilometer", "Centimeter", "Millimeter", "Mile", "Yard", "Foot", "Inch" }));
        a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        a.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        b.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        b.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meter", "Kilometer", "Centimeter", "Millimeter", "Mile", "Yard", "Foot", "Inch" }));

        x.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        y.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        convert.setBackground(new java.awt.Color(0, 102, 0));
        convert.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        convert.setForeground(new java.awt.Color(255, 255, 255));
        convert.setText("Convert");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setMaximumSize(new java.awt.Dimension(91, 27));
        jButton2.setMinimumSize(new java.awt.Dimension(91, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("=");

        jLabel2.setText("=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(convert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convert))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 10, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Return");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("StringEquality")
    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        double z;
        double value = Double.parseDouble(x.getText());
        if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Meter")
        {
            z = value;
            y.setText(""+z);
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Millimeter")
        {
            z = value * 1000;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Kilometer")
        {
            z = value / 1000;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Centimeter")
        {
            z = value * 100;
            y.setText(""+z);
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Foot")
        {
            z = value / 1609.35;
            y.setText(String.format("%.4f", z));
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Yard")
        {
            z = value / 0.9144;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Foot")
        {
            z = value / 0.3048;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Meter" && b.getSelectedItem().toString() == "Inch")
        {
            z = value * 39.37007874;
            y.setText(String.format("%.2f", z));
        }
        //-----------Kilo------------//
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Kilometer")
        {
            z = value;
            y.setText(""+z);
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Millimeter")
        {
            z = value * 1000000;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Meter")
        {
            z = value * 1000;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Centimeter")
        {
            z = value * 100000;
            y.setText(""+z);
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Foot")
        {
            z = value / 1.60935;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Yard")
        {
            z = value / 0.0009144;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Foot")
        {
            z = value / 0.0003048;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Kilometer" && b.getSelectedItem().toString() == "Inch")
        {
            z = value * 39370.07874;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Meter") {
            z = value / 100;
            y.setText(String.format("%.3f", z));
        }
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Centimeter") {
            z = value;
            y.setText(String.format("%.3f", z));
        } 
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Kilometer") {
            z = value / 100000;
            y.setText(String.format("%.3f", z));
        }
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Yard")
        {
            z = value / 91.44;
            y.setText(String.format("%.2f", z));
        }
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Millimeter") {
            z = value * 10;
            y.setText(String.format("%.3f", z));
        }
        else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Foot") {
            z = value / 160935;
            y.setText(String.format("%.3f", z));

        } else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Foot") {
            z = value / 30.48;
            y.setText(String.format("%.3f", z));

        } else if (a.getSelectedItem().toString() == "Centimeter" && b.getSelectedItem().toString() == "Inch") {
            z = value / 2.54;
            y.setText(String.format("%.3f", z));
        }
        //-------------------------------------------------------------//
        //-------------------Foot--------------------------------------//
        //-------------------------------------------------------------//
         else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Meter") {
            z = value * 1609;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Centimeter") {
            z = value * 160900;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Kilometer") {
            z = value * 1.609;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Foot") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Mile") {
            z = value / 5280;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Inch") {
            z = value * 63360;
            y.setText(String.format("%.3f", z));
        } 
         else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Millimeter") {
            z = value * 1609350;
            y.setText(String.format("%.3f", z));
        } 
         else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Yard") {
            z = value * 1760.0065617;
            y.setText(String.format("%.3f", z));
        } 
        //-------------------------------------------------------------//
        //-------------------Foot--------------------------------------//
        //-------------------------------------------------------------//
        else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Meter") {
            z = value / 3.281;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Centimeter") {
            z = value * 30.48;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Kilometer") {
            z = value / 3281;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Foot") {
            z = value / 5280;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Foot") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Inch") {
            z = value * 12;
            y.setText(String.format("%.3f", z));
        }
         else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Millimeter") {
            z = value * 304.8;
            y.setText(String.format("%.3f", z));
        } 
         else if (a.getSelectedItem().toString() == "Foot" && b.getSelectedItem().toString() == "Yard") {
            z = value /3;
            y.setText(String.format("%.3f", z));
        } 
        //-------------------------------------------------------------//
        //-------------------Inch--------------------------------------//
        //-------------------------------------------------------------//
        else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Meter") {
            z = value / 39.37;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Centimeter") {
            z = value * 2.54;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Kilometer") {
            z = value / 39370;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Mile") {
            z = value / 63360;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Foot") {
            z = value / 12;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Millimeter") {
            z = value * 25.4;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Yard") {
            z = value / 36;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Inch" && b.getSelectedItem().toString() == "Inch") {
            z = value;
            y.setText(String.format("%.3f", z));
        }
        //-------------------------------------------------------------//
        //-------------------Yard--------------------------------------//
        //-------------------------------------------------------------//
        else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Meter") {
            z = value * 0.9144;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Centimeter") {
            z = value * 91.44;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Kilometer") {
            z = value * 0.0009144;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Mile") {
            z = value / 1760.0065617;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Foot") {
            z = value * 3;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Inch") {
            z = value * 12;
            y.setText(String.format("%.3f", z));
        } else if (a.getSelectedItem().toString() == "Yard" && b.getSelectedItem().toString() == "Yard") {
            z = value;
            y.setText(String.format("%.3f", z));
        }
        
    }//GEN-LAST:event_convertActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        x.setText(null);
        y.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Length().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox a;
    private javax.swing.JComboBox b;
    private javax.swing.JButton convert;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
